### ISSUE TITLE
Eject to bare workflow umbrella issue

### ISSUE THREAD

**Issue by cruzach** [expo/expo-cli#1494]
## Description

Ejecting to bare is going to get a lot more popular, this is an umbrella issue for all the improvements we can make to provide a smooth ejection process

- [x] Better error checking on `expo eject` (check for spaces, even if in non-interactive) 
- [x] escape characters for XML (values that go into `info.plist` or `AndroidManifest.xml`)
- [x] alert if you're importing anything from the `expo` package (no modules left to import from the expo package now 👍 )
- [ ] warn if you're relying on `Constants.manifest` anywhere (maybe this *will* be supported with the bare OTA module?)
- [x] if you try to run a command that expo doesn't support for bare, it should let you know

Apply app-specific config, if one of these keys are present in `app.json`:
- [x] version
- [x] orientation
- [x] userInterfaceStyle - also iOS and android specific values. default to `light`
- [x] Splash- also iOS and android specific values
- [x] backgroundColor - also iOS and android specific values
- [x] primaryColor
- [x] icon  also iOS and android specific values
- [x] androidStatusBar
- [x] androidNavigationBar 
- [x] scheme
- [x] locales
- [x] owner

iOS: 
- [x] buildNumber
- [x] “Config” object - branch, usesNonExemptEncryption, googleMapsApiKey, googleMobileAdsAppId, googleMobileAdsAutoInit,  googleSignIn
- [x] googleServicesFile
- [x] supportsTablet
- [x] istabletonly
- [x] infoPlist
- [x] associatedDomains
- [x] usesAppleSignIn
- [x] usesIcloudStorage
- [x] accessesContactNotes

Android:
- [x] versionCode
- [x] can't use java reserved words for package name
- [x] adaptiveIcon
- [x] Permissions
- [x] googleServicesFile
- [x] “Config” object - branch, usesNonExemptEncryption, googleMapsApiKey, googleMobileAdsAppId, googleMobileAdsAutoInit,  googleSignIn
- [x] Splash
- [x] intentfilters

Facebook:
- [x] facebookappid
- [x] Facebookautoinitenabled
- [x] facebookAutoLogAppEventsEnabled
- [x] facebookAdvertiserIDCollectionEnabled
- [x] facebookDisplayName
- [x] facebookScheme

**Comment by brentvatne** [comment]
>  alert if you're importing anything from the expo package

it'd be nice to explore a better way to handle this, so the app still loads but we just give a meaningful warning about it

**Comment by cruzach** [comment]
Maybe add a check to those packages like `if(bare){ export nothing and console.warn("...") with a stack trace }`?

**Comment by brentvatne** [comment]
the tricky thing is that we import `Expo.fx` at the top of the `expo` pkg main (https://github.com/expo/expo/blob/d43a1d9b8a5bb7d487867c76d482d17599aebeb5/packages/expo/src/Expo.ts#L1) which in turns imports this [validation](https://github.com/expo/expo/blob/d43a1d9b8a5bb7d487867c76d482d17599aebeb5/packages/expo/src/environment/validate.fx.ts) script.

i think if there is a good way to do `if (bare) { ...` this will work. we might need to use the `.expo.js` file extension to make that possible.. unsure

**Comment by madhums** [comment]
Will this be released as part of sdk37? Any idea when it will be rolled out?

**Comment by brentvatne** [comment]
@madhums - yes, release alongside sdk37 is likely

**Comment by tiagodprovenzano** [comment]
Hey guys, I have an issue and I know you have already solved this. 

I had my app in the managed workflow for a while and now we are getting more user and I need a more powerfull local DB. So i ejected my app. Problem is, for noobness of mine my android packageName is "com.[...].new"

I have made all the adjustments necessary to build my project, but now android studio is telling it cant use this package name as "new" is a reserved word in Java. Curiously expo managed to build with this package name, so i know it is possible. 

Can anyone point me in the right direction?

**Comment by brentvatne** [comment]
you can leave the appication id as is and change the package name accordingly. learn more at https://developer.android.com/studio/build/application-id.html

> I had my app in the managed workflow for a while and now we are getting more user and I need a more powerfull local DB.

did you consider using sqlite?

**Comment by brentvatne** [comment]
cc @cruzach - this is something we should consider when applying the android.package - we can't use java reserved words

**Comment by tiagodprovenzano** [comment]
> you can leave the appication id as is and change the package name accordingly. learn more at https://developer.android.com/studio/build/application-id.html
> 
> > I had my app in the managed workflow for a while and now we are getting more user and I need a more powerfull local DB.
> 
> did you consider using sqlite?

Thank you for your reply! Lifesaver... I`ll have a look at the article. 

Currently we do use sqlite but the volume of data we have is just to big. The limitations of the number of variables per transaction makes it too slow on android devices. Writing takes about 10x more time in android than ios.

**Comment by EvanBacon** [comment]
I don't think Constants.manifest is in scope for the eject command. Last feature has been implemented with #2687
