### ISSUE TITLE
Updated Engineering & Design Task List

### ISSUE THREAD

**Issue by jimmylee** [expo/expo-cli#7]
- [x] **Blocking** - Critical issues appearing as the default window.
- [x] **Blocking** - Entire page going black after a certain duration of time.
- [x] Add user information to graphQL query.
- [x] Show username in publish section url.
- [x] Rename critical issues to issues, use yellow for warnings, and red for blocking issues.
- [x] Selecting “tunnel” URL type has a long delay 
- [x] Add an indicator of unread logs in each log tab
- [x] Make it clearer how to exit the publish modal
- [x] Toasts shown after opening a simulator or sending the link never go away unless dismissed
- [x] Clicking the icon next to URL should copy the URL
- [x] Make the project name more prominent
- [x] Add a way to clear a log
- [x] *Critical:* node 10 bug - expo/universe#2552
- [x] *Critical:* closing the cli appears to have no impact on the web UI
- [x] Important: add interact prompt to expo-cli in the same way that it works for CRNA
- [x] Important: Change prefix from [exp] to [expo] or remove prefix entirely
- Important: expo ios and expo android should start packager and launch like on CRNA. -> https://github.com/expo/universe/issues/2671
- Remove the warning about not using the Expo fork of RN -> https://github.com/expo/universe/issues/2672
- **V2?** Disabling wifi should change the indicator in the browser -> https://github.com/expo/expo-dev-tools/issues/11
- **V2?** Change default from Tunnel to better option if there is one. -> https://github.com/expo/universe/issues/2673
